const fs = require('fs');
const path = require('path');

const locales = ['ar', 'de', 'en', 'es', 'fr', 'hi', 'id', 'it', 'ja', 'ko', 'ms', 'nl', 'pl', 'pt', 'ru', 'th', 'tr', 'uk', 'vi', 'zh'];

const translations = {
    en: {
        hero: { title: "The <highlight>Lifetime Legacy</highlight> <br /> For Indonesian Diaspora", description: "Preserving your blood bonds with Indonesia through the world's most robust Global Citizen of Indonesia residency status. Enjoy unlimited work rights, property ownership, and freedom of entry for a lifetime." },
        marquee: { item1: "Lifetime Residency Status", item2: "Full Work Rights", item3: "Diaspora Priority", item4: "Unlimited Re-Entry" },
        bonding: { title: "Preserving Bonds, Building Future", quote: "\"GCI is more than a permit; it is a declaration that the children of Indonesia, wherever they may be, will always have a home to return to.\"" },
        eligibility: { title: "Interactive Eligibility Filter", subtitle: "Select your profile to see GCI requirements", "4C": { title: "Eks-WNI (Former Citizen)", desc: "Specifically for those who held Indonesian citizenship in the past." }, "4D": { title: "Direct Descendants", desc: "For children and grandchildren of current or former Indonesian citizens." }, "4H": { title: "Global Talent Diaspora", desc: "For high-achieving diaspora members with specialized expertise or investment potential." } },
        benefits: { stay: { title: "Unlimited Stay", desc: "No more extensions. Your status is permanent as long as eligibility criteria are met." }, work: { title: "Work Rights", desc: "Work freely in Indonesia without the need for a separate IMTA or Work Permit." }, property: { title: "Property Ownership", desc: "Easier path to owning property in Indonesia compared to standard foreign permits." }, entry: { title: "Re-Entry Freedom", desc: "Multiple re-entry permits valid for a lifetime. Fly in and out freely." } },
        advantage: { title: "The GCI Advantage", table: { feature: "Feature", gci: "GCI Status", golden: "Golden Visa", kitas: "ITAS/ITAP", validity_label: "Validity", unlimited: "UNLIMITED", investment_label: "Investment Req", none: "NONE (Blood Bond)" } },
        security: { title: "Secured by <highlight>IDiv Infinity™</highlight>", desc: "Your GCI status is issued with a specialized Gold Variant IDiv Card, featuring the unique infinity icon—a mark of your lifetime bond with Indonesia.", feature1: "Smart QR Verification", feature2: "Dual-Layer Hologram", feature3: "Lifetime Status Check" },
        cta: { title: "Ready to Preserve Your Legacy?", subtitle: "Join the Global Citizen program today with our expert legal team.", placeholder: "Email Address", button: "Start Application" },
        activity: { secured: "Just secured GCI Verification", applying: "Applying for GCI Benefits", researching: "Researching Property Rights", verifying: "Verifying Diaspora Status" }
    },
    id: {
        hero: { title: "Warisan <highlight>Seumur Hidup</highlight> <br /> Bagi Diaspora Indonesia", description: "Menjaga ikatan darah Anda dengan Indonesia melalui status kependudukan Global Citizen of Indonesia (GCI) yang paling kuat di dunia. Nikmati hak kerja tanpa batas, kepemilikan properti, dan kebebasan masuk seumur hidup." },
        marquee: { item1: "Status Kependudukan Seumur Hidup", item2: "Hak Kerja Lengkap", item3: "Prioritas Diaspora", item4: "Masuk Kembali Tanpa Batas" },
        bonding: { title: "Menjaga Ikatan, Membangun Masa Depan", quote: "\"GCI lebih dari sekadar izin; ini adalah pernyataan bahwa anak-anak Indonesia, di mana pun mereka berada, akan selalu memiliki rumah untuk pulang.\"" },
        eligibility: { title: "Filter Kelayakan Interaktif", subtitle: "Pilih profil Anda untuk melihat persyaratan GCI", "4C": { title: "Eks-WNI", desc: "Khusus bagi mereka yang pernah memegang kewarganegaraan Indonesia di masa lalu." }, "4D": { title: "Keturunan Langsung", desc: "Untuk anak dan cucu dari warga negara Indonesia saat ini atau mantan warga negara Indonesia." }, "4H": { title: "Diaspora Talenta Global", desc: "Untuk anggota diaspora berprestasi tinggi dengan keahlian khusus atau potensi investasi." } },
        benefits: { stay: { title: "Tinggal Tanpa Batas", desc: "Tidak ada lagi perpanjangan. Status Anda permanen selama kriteria kelayakan terpenuhi." }, work: { title: "Hak Kerja", desc: "Bekerja bebas di Indonesia tanpa memerlukan IMTA atau Izin Kerja terpisah." }, property: { title: "Kepemilikan Properti", desc: "Jalur lebih mudah untuk memiliki properti di Indonesia dibandingkan izin asing standar." }, entry: { title: "Kebebasan Masuk Kembali", desc: "Izin masuk kembali berkali-kali yang berlaku seumur hidup. Terbang masuk dan keluar dengan bebas." } },
        advantage: { title: "Keunggulan GCI", table: { feature: "Fitur", gci: "Status GCI", golden: "Golden Visa", kitas: "ITAS/ITAP", validity_label: "Validitas", unlimited: "TANPA BATAS", investment_label: "Syarat Investasi", none: "TIDAK ADA (Ikatan Darah)" } },
        security: { title: "Diamankan oleh <highlight>IDiv Infinity™</highlight>", desc: "Status GCI Anda diterbitkan dengan Kartu IDiv Varian Emas khusus, menampilkan ikon infinity yang unik—tanda ikatan seumur hidup Anda dengan Indonesia.", feature1: "Verifikasi QR Pintar", feature2: "Hologram Dua Lapis", feature3: "Pengecekan Status Seumur Hidup" },
        cta: { title: "Siap Menjaga Warisan Anda?", subtitle: "Bergabunglah dengan program Global Citizen hari ini bersama tim hukum ahli kami.", placeholder: "Alamat Email", button: "Mulai Aplikasi" },
        activity: { secured: "Baru saja mengamankan Verifikasi GCI", applying: "Sedang mengajukan Manfaat GCI", researching: "Meneliti Hak Properti", verifying: "Memverifikasi Status Diaspora" }
    },
    ar: {
        hero: { title: "الإرث <highlight>مدى الحياة</highlight> <br /> للشتات الإندونيسي", description: "الحفاظ على روابط الدم مع إندونيسيا من خلال أقوى وضع إقامة للمواطن العالمي في إندونيسيا (GCI). تمتع بحقوق عمل غير محدودة، وملكية العقارات، وحرية الدخول مدى الحياة." },
        marquee: { item1: "وضع إقامة مدى الحياة", item2: "حقوق عمل كاملة", item3: "أولوية الشتات", item4: "إعادة دخول غير محدودة" },
        bonding: { title: "الحفاظ على الروابط، بناء المستقبل", quote: "\"GCI هو أكثر من مجرد تصريح؛ إنه إعلان بأن أطفال إندونيسيا، أينما كانوا، سيكون لديهم دائمًا وطن ليعودوا إليه.\"" },
        eligibility: { title: "فلتر الأهلية التفاعلي", subtitle: "اختر ملفك الشخصي لرؤية متطلبات GCI", "4C": { title: "مواطن إندونيسي سابق", desc: "خاص لأولئك الذين حملوا الجنسية الإندونيسية في الماضي." }, "4D": { title: "المنحدرين المباشرين", desc: "للأطفال والأحفاد من مواطني إندونيسيا الحاليين أو السابقين." }, "4H": { title: "شتات المواهب العالمية", desc: "لأعضاء الشتات ذوي الإنجازات العالية بخبرات متخصصة." } },
        benefits: { stay: { title: "إقامة غير محدودة", desc: "لا مزيد من التمديدات. وضعك دائم طالما تم استيفاء معايير الأهلية." }, work: { title: "حقوق العمل", desc: "العمل بحرية في إندونيسيا دون الحاجة إلى تصريح عمل منفصل." }, property: { title: "ملكيات العقارات", desc: "طريق أسهل لامتلاك العقارات في إندونيسيا مقارنة بالتصاريح الأجنبية العادية." }, entry: { title: "حرية إعادة الدخول", desc: "تصاريح إعادة دخول متعددة صالحة مدى الحياة. سافر بحرية." } },
        advantage: { title: "ميزة GCI", table: { feature: "Feature", gci: "وضع GCI", golden: "التأشيرة الذهبية", kitas: "ITAS/ITAP", validity_label: "الصلاحية", unlimited: "غير محدود", investment_label: "متطلبات الاستثمار", none: "لا يوجد (رابط دم)" } },
        security: { title: "مؤمن بواسطة <highlight>IDiv Infinity™</highlight>", desc: "يتم إصدار وضع GCI الخاص بك مع بطاقة IDiv الذهبية المتخصصة، التي تتميز بأيقونة اللانهاية الفريدة - علامة على رابطك مدى الحياة مع إندونيسيا.", feature1: "تحقق QR ذكي", feature2: "هولوغرام ثنائي الطبقة", feature3: "فحص الحالة مدى الحياة" },
        cta: { title: "هل أنت مستعد للحفاظ على إرثك؟", subtitle: "انضم إلى برنامج المواطن العالمي اليوم مع فريقنا القانوني الخبير.", placeholder: "عنوان البريد الإلكتروني", button: "ابدأ الطلب" },
        activity: { secured: "تم تأمين تحقق GCI للتو", applying: "التقدم للحصول على مزايا GCI", researching: "البحث في حقوق الملكية", verifying: "التحقق من حالة الشتات" }
    },
    de: {
        hero: { title: "Das <highlight>Lebenslange Erbe</highlight> <br /> Für die indonesische Diaspora", description: "Bewahren Sie Ihre Blutsbande zu Indonesien durch den weltweit robustesten Aufenthaltsstatus als Global Citizen of Indonesia (GCI). Genießen Sie lebenslang unbegrenzte Arbeitsrechte, Immobilieneigentum und Einreisefreiheit." },
        marquee: { item1: "Lebenslanger Residenzstatus", item2: "Volle Arbeitsrechte", item3: "Diaspora-Priorität", item4: "Unbegrenzte Re-Entry" },
        bonding: { title: "Bindungen bewahren, Zukunft bauen", quote: "\"GCI ist mehr als eine Erlaubnis; es ist eine Erklärung, dass die Kinder Indonesiens, wo auch immer sie sein mögen, immer ein Zuhause haben werden, zu dem sie zurückkehren können.\"" },
        eligibility: { title: "Interaktiver Eignungsfilter", subtitle: "Wählen Sie Ihr Profil, um die GCI-Anforderungen zu sehen", "4C": { title: "Eks-WNI (Ehemalige Staatsbürger)", desc: "Speziell für diejenigen, die in der Vergangenheit die indonesische Staatsbürgerschaft besaßen." }, "4D": { title: "Direkte Nachkommen", desc: "Für Kinder und Enkelkinder aktueller oder ehemaliger indonesischer Staatsbürger." }, "4H": { title: "Global Talent Diaspora", desc: "Für hochqualifizierte Diaspora-Mitglieder mit spezialisierter Expertise." } },
        benefits: { stay: { title: "Unbegrenzter Aufenthalt", desc: "Keine Verlängerungen mehr. Ihr Status ist dauerhaft, solange die Kriterien erfüllt sind." }, work: { title: "Arbeitsrechte", desc: "Arbeiten Sie frei in Indonesien, ohne ein separates IMTA oder Arbeitserlaubnis zu benötigen." }, property: { title: "Immobilieneigentum", desc: "Einfacherer Weg zum Immobilieneigentum im Vergleich zu ausländischen Standardgenehmigungen." }, entry: { title: "Einreisefreiheit", desc: "Mehrfache Wiedereinreise-Genehmigungen, die ein Leben lang gültig sind. Fliegen Sie frei ein und aus." } },
        advantage: { title: "Der GCI-Vorteil", table: { feature: "Merkmal", gci: "GCI-Status", golden: "Golden Visa", kitas: "ITAS/ITAP", validity_label: "Gültigkeit", unlimited: "UNBEGRENZT", investment_label: "Investitionsanforderung", none: "KEINE (Blutsbande)" } },
        security: { title: "Gesichert durch <highlight>IDiv Infinity™</highlight>", desc: "Ihr GCI-Status wird mit einer speziellen Gold Variant IDiv Card ausgestellt, die das einzigartige Infinity-Icon trägt – ein Zeichen Ihrer lebenslangen Bindung zu Indonesien.", feature1: "Smarte QR-Verifizierung", feature2: "Dual-Layer Hologramm", feature3: "Lebenslanger Status-Check" },
        cta: { title: "Bereit, Ihr Erbe zu bewahren?", subtitle: "Treten Sie noch heute dem Global Citizen Programm mit unserem Experten-Team bei.", placeholder: "E-Mail-Adresse", button: "Antrag starten" },
        activity: { secured: "Gerade GCI-Verifizierung gesichert", applying: "GCI-Vorteile beantragen", researching: "Eigentumsrechte recherchieren", verifying: "Diaspora-Status verifizieren" }
    },
    es: {
        hero: { title: "El <highlight>Legado de por vida</highlight> <br /> para la diáspora indonesia", description: "Preserve sus lazos de sangre con Indonesia a través del estatus de residencia Global Citizen of Indonesia (GCI) más robusto del mundo. Disfrute de derechos laborales ilimitados, propiedad de bienes raíces y libertad de entrada de por vida." },
        marquee: { item1: "Estatus de residencia de por vida", item2: "Plenos derechos laborales", item3: "Prioridad para la diáspora", item4: "Reentrada ilimitada" },
        bonding: { title: "Preservando lazos, construyendo futuro", quote: "\"El GCI es más que un permiso; es una declaración de que los hijos de Indonesia, dondequiera que estén, siempre tendrán un hogar al que regresar.\"" },
        eligibility: { title: "Filtro de elegibilidad interactivo", subtitle: "Seleccione su perfil para ver los requisitos del GCI", "4C": { title: "Ex-WNI (Ex ciudadanos)", desc: "Específicamente para aquellos que poseyeron la ciudadanía indonesia en el pasado." }, "4D": { title: "Descendientes directos", desc: "Para hijos y nietos de ciudadanos indonesios actuales o anteriores." }, "4H": { title: "Diáspora de talento global", desc: "Para miembros de la diáspora de alto rendimiento con experiencia especializada." } },
        benefits: { stay: { title: "Estancia ilimitada", desc: "No más extensiones. Su estatus es permanente mientras se cumplan los criterios de elegibilidad." }, work: { title: "Derechos laborales", desc: "Trabaje libremente en Indonesia sin necesidad de un permiso de trabajo por separado." }, property: { title: "Propiedad de bienes raíces", desc: "Camino más fácil para poseer propiedades en Indonesia en comparación con los permisos extranjeros estándar." }, entry: { title: "Libertad de reentrada", desc: "Permisos de reentrada múltiples válidos de por vida. Viaje libremente." } },
        advantage: { title: "La ventaja del GCI", table: { feature: "Característica", gci: "Estatus GCI", golden: "Visa Dorada", kitas: "ITAS/ITAP", validity_label: "Validez", unlimited: "ILIMITADO", investment_label: "Requisito de inversión", none: "NINGUNO (Lazo de sangre)" } },
        security: { title: "Asegurado por <highlight>IDiv Infinity™</highlight>", desc: "Su estatus GCI se emite con una tarjeta IDiv Variant Gold especializada, con el icono infinity único, una marca de su vínculo de por vida con Indonesia.", feature1: "Verificación QR inteligente", feature2: "Holograma de doble capa", feature3: "Verificación de estatus de por vida" },
        cta: { title: "¿Listo para preservar su legado?", subtitle: "Únase al programa Global Citizen hoy mismo con nuestro equipo legal experto.", placeholder: "Correo electrónico", button: "Iniciar solicitud" },
        activity: { secured: "Acaba de asegurar la verificación GCI", applying: "Solicitando beneficios de GCI", researching: "Investigando derechos de propiedad", verifying: "Verificando estatus de diáspora" }
    },
    fr: {
        hero: { title: "L'héritage <highlight>à vie</highlight> <br /> Pour la diaspora indonésienne", description: "Préservez vos liens du sang avec l'Indonésie grâce au statut de résident Global Citizen of Indonesia (GCI) le plus robuste au monde. Profitez de droits de travail illimités, de la propriété immobilière et de la liberté d'entrée à vie." },
        marquee: { item1: "Statut de résidence à vie", item2: "Droits de travail complets", item3: "Priorité à la diaspora", item4: "Réentré illimité" },
        bonding: { title: "Préserver les liens, construire l'avenir", quote: "\"Le GCI est plus qu'un permis ; c'est une déclaration que les enfants de l'Indonésie, où qu'ils soient, auront toujours un foyer où revenir.\"" },
        eligibility: { title: "Filtre d'éligibilité interactif", subtitle: "Sélectionnez votre profil pour voir les exigences du GCI", "4C": { title: "Ex-WNI (Anciens citoyens)", desc: "Spécifiquement pour ceux qui ont détenu la citoyenneté indonésienne dans le passé." }, "4D": { title: "Descendants directs", desc: "Pour les enfants et petits-enfants de citoyens indonésiens actuels ou anciens." }, "4H": { title: "Diaspora des talents mondiaux", desc: "Pour les membres de la diaspora hautement qualifiés ayant une expertise spécialisée." } },
        benefits: { stay: { title: "Séjour illimité", desc: "Plus d'extensions. Votre statut est permanent tant que les critères d'éligibilité sont remplis." }, work: { title: "Droits de travail", desc: "Travaillez librement en Indonésie sans avoir besoin d'un permis de travail séparé." }, property: { title: "Propriété immobilière", desc: "Chemin plus facile pour posséder une propriété en Indonésie par rapport aux permis étrangers standard." }, entry: { title: "Liberté de réentrée", desc: "Permis de réentrée multiples valables à vie. Voyagez librement." } },
        advantage: { title: "L'avantage GCI", table: { feature: "Caractéristique", gci: "Statut GCI", golden: "Golden Visa", kitas: "ITAS/ITAP", validity_label: "Validité", unlimited: "ILLIMITÉ", investment_label: "Exigence d'investissement", none: "AUCUNE (Lien du sang)" } },
        security: { title: "Sécurisé par <highlight>IDiv Infinity™</highlight>", desc: "Votre statut GCI est délivré avec une carte IDiv Variante Or spécialisée, arborant l'icône unique infinity — une marque de votre lien à vie avec l'Indonésie.", feature1: "Vérification QR intelligente", feature2: "Hologramme double couche", feature3: "Vérification du statut à vie" },
        cta: { title: "Prêt à préserver votre héritage ?", subtitle: "Rejoignez le programme Global Citizen dès aujourd'hui avec notre équipe juridique experte.", placeholder: "Adresse e-mail", button: "Démarrer la demande" },
        activity: { secured: "Vient de sécuriser la vérification GCI", applying: "Demande de prestations GCI", researching: "Recherche sur les droits de propriété", verifying: "Vérification du statut de diaspora" }
    },
    it: {
        hero: { title: "L'eredità <highlight>a vita</highlight> <br /> Per la diaspora indonesiana", description: "Preserva i tuoi legami di sangue con l'Indonesia attraverso lo status di residenza Global Citizen of Indonesia (GCI) più robusto al mondo. Goditi diritti di lavoro illimitati, proprietà immobiliare e libertà d'ingresso a vita." },
        marquee: { item1: "Status di residenza a vita", item2: "Pieni diritti di lavoro", item3: "Priorità alla diaspora", item4: "Rientro illimitato" },
        bonding: { title: "Preservare i legami, costruire il futuro", quote: "\"Il GCI è più di un permesso; è una dichiarazione che i figli dell'Indonesia, ovunque si trovino, avranno sempre una casa dove tornare.\"" },
        eligibility: { title: "Filtro di idoneità interattivo", subtitle: "Seleziona il tuo profilo per vedere i requisiti GCI", "4C": { title: "Ex-WNI (Ex cittadini)", desc: "Specificamente per coloro che hanno detenuto la cittadinanza indonesiana in passato." }, "4D": { title: "Discendenti diretti", desc: "Per figli e nipoti di cittadini indonesiani attuali o precedenti." }, "4H": { title: "Diaspora dei talenti globali", desc: "Per membri della diaspora ad alto rendimento con competenze specializzate." } },
        benefits: { stay: { title: "Soggiorno illimitato", desc: "Niente più estensioni. Il tuo status è permanente finché i criteri di idoneità sono soddisfatti." }, work: { title: "Diritti di lavoro", desc: "Lavora liberamente in Indonesia senza necessità di un permesso di lavoro separato." }, property: { title: "Proprietà immobiliare", desc: "Percorso più semplice per possedere proprietà in Indonesia rispetto ai permessi stranieri standard." }, entry: { title: "Libertà di rientro", desc: "Permessi di rientro multipli validi a vita. Viaggia liberamente." } },
        advantage: { title: "Il vantaggio GCI", table: { feature: "Caratteristica", gci: "Status GCI", golden: "Golden Visa", kitas: "ITAS/ITAP", validity_label: "Validità", unlimited: "ILLIMITATO", investment_label: "Requisito di investimento", none: "NESSUNO (Legame di sangue)" } },
        security: { title: "Protetto da <highlight>IDiv Infinity™</highlight>", desc: "Il tuo status GCI viene rilasciato con una carta IDiv variante oro specializzata, con l'icona infinity unica—un segno del tuo legame a vita con l'Indonesia.", feature1: "Verifica QR intelligente", feature2: "Ologramma a doppio strato", feature3: "Controllo stato a vita" },
        cta: { title: "Pronto a preservare la tua eredità?", subtitle: "Unisciti al programma Global Citizen oggi stesso con il nostro team legale esperto.", placeholder: "Indirizzo e-mail", button: "Inizia la domanda" },
        activity: { secured: "Ha appena ottenuto la verifica GCI", applying: "Richiesta di benefici GCI", researching: "Ricerca sui diritti di proprietà", verifying: "Verifica dello status di diaspora" }
    },
    it: {
        hero: { title: "L'eredità <highlight>a vita</highlight> <br /> Per la diaspora indonesiana", description: "Preserva i tuoi legami di sangue con l'Indonesia attraverso lo status di residenza Global Citizen of Indonesia (GCI) più robusto al mondo. Goditi diritti di lavoro illimitati, proprietà immobiliare e libertà d'ingresso a vita." },
        marquee: { item1: "Status di residenza a vita", item2: "Pieni diritti di lavoro", item3: "Priorità alla diaspora", item4: "Rientro illimitato" },
        bonding: { title: "Preservare i legami, costruire il futuro", quote: "\"Il GCI è più di un permesso; è una dichiarazione che i figli dell'Indonesia, ovunque si trovino, avranno sempre una casa dove tornare.\"" },
        eligibility: { title: "Filtro di idoneità interattivo", subtitle: "Seleziona il tuo profilo per vedere i requisiti GCI", "4C": { title: "Ex-WNI (Ex cittadini)", desc: "Specificamente per coloro che hanno detenuto la cittadinanza indonesiana in passato." }, "4D": { title: "Discendenti diretti", desc: "Per figli e nipoti di cittadini indonesiani attuali o precedenti." }, "4H": { title: "Diaspora dei talenti globali", desc: "Per membri della diaspora ad alto rendimento con competenze specializzate." } },
        benefits: { stay: { title: "Soggiorno illimitato", desc: "Niente più estensioni. Il tuo status è permanente finché i criteri di idoneità sono soddisfatti." }, work: { title: "Diritti di lavoro", desc: "Lavora liberamente in Indonesia senza necessità di un permesso di lavoro separato." }, property: { title: "Proprietà immobiliare", desc: "Percorso più semplice per possedere proprietà in Indonesia rispetto ai permessi stranieri standard." }, entry: { title: "Libertà di rientro", desc: "Permessi di rientro multipli validi a vita. Viaggia liberamente." } },
        advantage: { title: "Il vantaggio GCI", table: { feature: "Caratteristica", gci: "Status GCI", golden: "Golden Visa", kitas: "ITAS/ITAP", validity_label: "Validità", unlimited: "ILLIMITATO", investment_label: "Requisito di investimento", none: "NESSUNO (Legame di sangue)" } },
        security: { title: "Protetto da <highlight>IDiv Infinity™</highlight>", desc: "Il tuo status GCI viene rilasciato con una carta IDiv variante oro specializzata, con l'icona infinity unica—un segno del tuo legame a vita con l'Indonesia.", feature1: "Verifica QR intelligente", feature2: "Ologramma a doppio strato", feature3: "Controllo stato a vita" },
        cta: { title: "Pronto a preservare la tua eredità?", subtitle: "Unisciti al programma Global Citizen oggi stesso con il nostro team legale esperto.", placeholder: "Indirizzo e-mail", button: "Inizia la domanda" },
        activity: { secured: "Ha appena ottenuto la verifica GCI", applying: "Richiesta di benefici GCI", researching: "Ricerca sui diritti di proprietà", verifying: "Verifica dello status di diaspora" }
    },
    ja: {
        hero: { title: "インドネシア・ディアスポラの <br /> <highlight>生涯にわたる遺産</highlight>", description: "世界で最も強力なインドネシア・グローバル・シチズン（GCI）居住資格を通じて、インドネシアとの血の絆を維持しましょう。生涯にわたる無制限の就労権利、不動産所有、および入国の自由を享受できます。" },
        marquee: { item1: "生涯居住ステータス", item2: "完全な就労権利", item3: "ディアスポラ優先", item4: "無制限の再入国" },
        bonding: { title: "絆を守り、未来を築く", quote: "「GCIは単なる許可証ではありません。インドネシアの子どもたちがどこにいても、いつでも帰れる家があるという宣言なのです。」" },
        eligibility: { title: "インタラクティブな資格フィルター", subtitle: "プロフィールを選択してGCI要件を確認", "4C": { title: "元インドネシア国民", desc: "過去にインドネシア国籍を保持していた方専用です。" }, "4D": { title: "直系の子孫", desc: "現または元のインドネシア国民の子および孫が対象です。" }, "4H": { title: "グローバル・タレント・ディアスポラ", desc: "専門的な専門知識や投資ポテンシャルを持つ優秀なディアスポラ向けです。" } },
        benefits: { stay: { title: "無制限の滞在", desc: "更新はもう不要です。資格基準を満たしている限り、ステータスは恒久的です。" }, work: { title: "就労権利", desc: "別の就労許可（IMTA）を必要とせずに、インドネシアで自由に働くことができます。" }, property: { title: "不動産所有", desc: "標準的な外国人向け許可と比較して、インドネシアでの不動産所有への道が容易になります。" }, entry: { title: "再入国の自由", desc: "生涯有効な数次再入国許可。自由に出入国できます。" } },
        advantage: { title: "GCIのメリット", table: { feature: "特徴", gci: "GCIステータス", golden: "ゴールデンビザ", kitas: "ITAS/ITAP", validity_label: "有効期限", unlimited: "無制限", investment_label: "投資要件", none: "なし（血の絆）" } },
        security: { title: "<highlight>IDiv Infinity™</highlight> によるセキュリティ", desc: "GCIステータスは、独自のインフィニティ・アイコンを備えた専用のゴールド・バリアントIDivカードとともに発行されます。これは、インドネシアとの生涯にわたる絆の証です。", feature1: "スマートQR照合", feature2: "2層ホログラム", feature3: "生涯ステータスチェック" },
        cta: { title: "遺産を守る準備はできていますか？", subtitle: "専門の法務チームとともに、今すぐグローバル・シチズン・プログラムに参加しましょう。", placeholder: "メールアドレス", button: "申請を開始する" },
        activity: { secured: "GCI認証を完了しました", applying: "GCI特典の申請中", researching: "不動産権利の調査中", verifying: "ディアスポラ資格の確認中" }
    },
    ko: {
        hero: { title: "인도네시아 디아스포라를 위한 <br /> <highlight>평생 유산</highlight>", description: "세계에서 가장 강력한 인도네시아 글로벌 시민(GCI) 거주 자격을 통해 인도네시아와의 혈연 관계를 보존하십시오. 평생 무제한 취업 권리, 부동산 소유권 및 입국 자유를 누리십시오." },
        marquee: { item1: "평생 거주 상태", item2: "전체 취업 권리", item3: "디아스포라 우선", item4: "무제한 재입국" },
        bonding: { title: "유대 보존, 미래 구축", quote: "\"GCI는 단순한 허가가 아닙니다. 인도네시아의 자녀들이 어디에 있든 항상 돌아올 집이 있다는 선언입니다.\"" },
        eligibility: { title: "대화형 자격 필터", subtitle: "GCI 요건 확인을 위해 프로필 선택", "4C": { title: "전 인도네시아 시민", desc: "과거 인도네시아 국籍을 보유했던 분들을 위한 전용 자격입니다." }, "4D": { title: "직계 후손", desc: "현재 또는 과거 인도네시아 시민의 자녀 및 손자녀를 위한 자격입니다." }, "4H": { title: "글로벌 인재 디아스포라", desc: "전문 지식이나 투자 잠재력을 가진 우수한 디아스포라 구성원을 위한 자격입니다." } },
        benefits: { stay: { title: "무제한 체류", desc: "더 이상의 연장은 없습니다. 자격 요건을 충족하는 한 상태는 영구적입니다." }, work: { title: "취업 권리", desc: "별도의 취업 허가 없이 인도네시아에서 자유롭게 근무할 수 있습니다." }, property: { title: "부동산 소유권", desc: "표준 외국인 허가에 비해 인도네시아에서 부동산을 소유할 수 있는 더 쉬운 길을 제공합니다." }, entry: { title: "재입국 자유", desc: "평생 유효한 복수 재입국 허가. 자유로운 출입국이 가능합니다." } },
        advantage: { title: "GCI 혜택", table: { feature: "기능", gci: "GCI 상태", golden: "골든 비자", kitas: "ITAS/ITAP", validity_label: "유효 기간", unlimited: "무제한", investment_label: "투자 요건", none: "없음 (혈연)" } },
        security: { title: "<highlight>IDiv Infinity™</highlight>로 보호됨", desc: "GCI 자격은 고유한 인피니티 아이콘이 특징인 전용 골드 변형 IDiv 카드와 함께 발급됩니다. 이는 인도네시아와의 평생 유대를 상징합니다.", feature1: "스마트 QR 검증", feature2: "이중 레이어 홀로그램", feature3: "평생 상태 확인" },
        cta: { title: "당신의 유산을 보존할 준비가 되셨습니까?", subtitle: "전문 법률 팀과 함께 오늘 글로벌 시티즌 프로그램에 참여하십시오.", placeholder: "이메일 주소", button: "신청 시작" },
        activity: { secured: "방금 GCI 자격 확인 완료", applying: "GCI 혜택 신청 중", researching: "부동산 권리 조사 중", verifying: "디아스포라 상태 확인 중" }
    },
    nl: {
        hero: { title: "De <highlight>Levenslange Erfenis</highlight> <br /> Voor de Indonesische Diaspora", description: "Behoud uw bloedbanden met Indonesië via de meest robuuste Global Citizen of Indonesia (GCI) verblijfsstatus ter wereld. Geniet een leven lang van onbeperkte werkrechten, vastgoedbezit en vrijheid van toegang." },
        marquee: { item1: "Levenslange Verblijfsstatus", item2: "Volledige Werkrechten", item3: "Diaspora Prioriteit", item4: "Onbeperkte Re-entry" },
        bonding: { title: "Banden Behouden, Toekomst Bouwen", quote: "\"GCI is meer dan een vergunning; het is een verklaring dat de kinderen van Indonesië, waar ze ook zijn, altijd een thuis zullen hebben om naar terug te keren.\"" },
        eligibility: { title: "Interactief Geschiktheidsfilter", subtitle: "Selecteer uw profiel om de GCI-vereisten te zien", "4C": { title: "Eks-WNI (Voormalige Burgers)", desc: "Speciaal voor degenen die in het verleden de Indonesische nationaliteit hadden." }, "4D": { title: "Directe Afstammelingen", desc: "Voor kinderen en kleinkinderen van huidige of voormalige Indonesische burgers." }, "4H": { title: "Global Talent Diaspora", desc: "Voor hoogpresterende diasporaleden met gespecialiseerde expertise of investeringspotentieel." } },
        benefits: { stay: { title: "Onbeperkt Verblijf", desc: "Geen verlengingen meer. Uw status is permanent zolang aan de criteria wordt voldaan." }, work: { title: "Werkrechten", desc: "Werk vrij in Indonesië zonder de noodzaak van een aparte IMTA of werkvergunning." }, property: { title: "Vastgoedbezit", desc: "Gemakkelijker pad naar het bezitten van vastgoed vergeleken met standaard buitenlandse vergunningen." }, entry: { title: "Vrijheid van Re-entry", desc: "Meervoudige re-entry vergunningen die een leven lang geldig zijn. Vlieg vrij in en uit." } },
        advantage: { title: "Het GCI Voordeel", table: { feature: "Kenmerk", gci: "GCI-status", golden: "Gouden Visum", kitas: "ITAS/ITAP", validity_label: "Geldigheid", unlimited: "ONBEPERKT", investment_label: "Investeringsvereiste", none: "GEEN (Bloedband)" } },
        security: { title: "Beveiligd door <highlight>IDiv Infinity™</highlight>", desc: "Uw GCI-status wordt uitgegeven met een gespecialiseerde Gold Variant IDiv Card, voorzien van het unieke infinity-icoon—een teken van uw levenslange band met Indonesië.", feature1: "Slimme QR-verificatie", feature2: "Dual-Layer Hologram", feature3: "Levenslange Statuscontrole" },
        cta: { title: "Klaar om uw erfenis te behouden?", subtitle: "Sluit u vandaag nog aan bij het Global Citizen-programma met ons deskundige juridische team.", placeholder: "E-mailadres", button: "Start Aanvraag" },
        activity: { secured: "Zojuist GCI-verificatie beveiligd", applying: "GCI-voordelen aanvragen", researching: "Vastgoedrechten onderzoeken", verifying: "Diaspora-status verifiëren" }
    },
    zh: {
        hero: { title: "<highlight>终身传承</highlight> <br /> 献给印尼海外侨民", description: "通过全球最强大的印尼全球公民 (GCI) 居留身份，维护您与印尼的血脉联系。终身享有无限工作权、房产所有权和出入境自由。" },
        marquee: { item1: "终身居留身份", item2: "全面工作权", item3: "侨民优先", item4: "无限次入境" },
        bonding: { title: "守护纽带，共筑未来", quote: "\"GCI 不仅仅是一份许可；它是一个宣言，无论印尼的孩子们身在何处，永远都有一个可以回归的家。\"" },
        eligibility: { title: "互动资格筛选", subtitle: "选择您的背景查看 GCI 要求", "4C": { title: "前印尼公民", desc: "专门针对过去曾持有印尼国籍的人士。" }, "4D": { title: "直系后裔", desc: "针对现任或前任印尼公民的子女及孙子女。" }, "4H": { title: "全球人才侨民", desc: "针对具有专业专长或投资潜力的高成就侨民。" } },
        benefits: { stay: { title: "无限期居住", desc: "无需再延期。只要符合资格标准，您的身份就是永久的。" }, work: { title: "工作权", desc: "在印尼自由工作，无需单独的工作许可。" }, property: { title: "房产所有权", desc: "与标准外国许可相比，拥有印尼房产的路径更简便。" }, entry: { title: "出入境自由", desc: "终身有效的多次往返许可。自由进出印尼。" } },
        advantage: { title: "GCI 优势", table: { feature: "特征", gci: "GCI 身份", golden: "黄金签证", kitas: "ITAS/ITAP", validity_label: "有效期限", unlimited: "无限期", investment_label: "投资要求", none: "无（血脉联系）" } },
        security: { title: "由 <highlight>IDiv Infinity™</highlight> 保障", desc: "您的 GCI 身份将获得专属的金版 IDiv 卡，印有独特的无限图标——象征您与印尼的终身联系。", feature1: "智能 QR 验证", feature2: "双层全息防伪", feature3: "终身身份查询" },
        cta: { title: "准备好传承您的遗产了吗？", subtitle: "立即通过我们的专家法律团队加入全球公民计划。", placeholder: "电子邮件地址", button: "开始申请" },
        activity: { secured: "刚刚获得 GCI 验证", applying: "申请 GCI 福利", researching: "研究房产权利", verifying: "核实侨民身份" }
    },
    ru: {
        hero: { title: "Наследие <highlight>длиною в жизнь</highlight> <br /> для индонезийской диаспоры", description: "Сохраните кровные узы с Индонезией благодаря самому надежному в мире статусу резидента Global Citizen of Indonesia (GCI). Пользуйтесь неограниченными правами на работу, владением недвижимостью и свободой въезда пожизненно." },
        marquee: { item1: "Пожизненный статус резидента", item2: "Полные права на работу", item3: "Приоритет диаспоры", item4: "Неограниченный въезд" },
        bonding: { title: "Сохранение связей, строительство будущего", quote: "\"GCI — это больше, чем разрешение; это заявление о том, что у детей Индонезии, где бы они ни находились, всегда будет дом, в который можно вернуться.\"" },
        eligibility: { title: "Интерактивный фильтр соответствия", subtitle: "Выберите свой профиль, чтобы увидеть требования GCI", "4C": { title: "Экс-WNI (Бывшие граждане)", desc: "Специально для тех, кто в прошлом имел индонезийское гражданство." }, "4D": { title: "Прямые потомки", desc: "Для детей и внуков нынешних или бывших граждан Индонезии." }, "4H": { title: "Диаспора мировых талантов", desc: "Для высококвалифицированных членов диаспоры со специальными знаниями." } },
        benefits: { stay: { title: "Неограниченное пребывание", desc: "Больше никаких продлений. Ваш статус постоянен при соблюдении критериев." }, work: { title: "Права на работу", desc: "Свободно работайте в Индонезии без необходимости получения отдельного разрешения на работу." }, property: { title: "Владение недвижимостью", desc: "Более простой путь к владению недвижимостью по сравнению со стандартными разрешениями." }, entry: { title: "Свобода въезда", desc: "Многократные разрешения на въезд, действующие пожизненно. Свободно летайте туда и обратно." } },
        advantage: { title: "Преимущества GCI", table: { feature: "Особенность", gci: "Статус GCI", golden: "Золотая виза", kitas: "ITAS/ITAP", validity_label: "Срок действия", unlimited: "НЕОГРАНИЧЕН", investment_label: "Требования к инвестициям", none: "НЕТ (Кровные узы)" } },
        security: { title: "Защищено <highlight>IDiv Infinity™</highlight>", desc: "Ваш статус GCI подтверждается специальной картой IDiv Gold Variant с уникальной иконкой бесконечности — символом вашей пожизненной связи с Индонезией.", feature1: "Смарт-верификация QR", feature2: "Двухслойная голограмма", feature3: "Пожизненная проверка статуса" },
        cta: { title: "Готовы сохранить свое наследие?", subtitle: "Присоединяйтесь к программе Global Citizen сегодня с нашей командой юристов.", placeholder: "Электронная почта", button: "Начать оформление" },
        activity: { secured: "Только что получил верификацию GCI", applying: "Подача заявки на льготы GCI", researching: "Изучение прав на недвижимость", verifying: "Проверка статуса диаспоры" }
    },
    hi: {
        hero: { title: "इंडोनेशियाई प्रवासियों के लिए <br /> <highlight>जीवन पर्यंत विरासत</highlight>", description: "दुनिया की सबसे मजबूत ग्लोबल सिटीजन ऑफ इंडोनेशिया (GCI) रेजिडेंसी स्थिति के माध्यम से इंडोनेशिया के साथ अपने रक्त संबंधों को संरक्षित करें। जीवन भर असीमित कार्य अधिकार, संपत्ति स्वामित्व और प्रवेश की स्वतंत्रता का आनंद लें।" },
        marquee: { item1: "जीवन पर्यंत निवास स्थिति", item2: "पूर्ण कार्य अधिकार", item3: "प्रवासी प्राथमिकता", item4: "असीमित पुन: प्रवेश" },
        bonding: { title: "संबंधों को सुरक्षित रखना, भविष्य बनाना", quote: "\"GCI केवल एक परमिट से अधिक है; यह एक घोषणा है कि इंडोनेशिया के बच्चों का, वे चाहे कहीं भी हों, घर लौटने के लिए हमेशा एक घर होगा।\"" },
        eligibility: { title: "इंटरैक्टिव पात्रता फ़िल्टर", subtitle: "GCI आवश्यकताओं को देखने के लिए अपना प्रोफ़ाइल चुनें", "4C": { title: "पूर्व-WNI (पूर्व नागरिक)", desc: "विशेष रूप से उनके लिए जिन्होंने अतीत में इंडोनेशियाई नागरिकता धारण की थी।" }, "4D": { title: "प्रत्यक्ष वंशज", desc: "वर्तमान या पूर्व इंडोनेशियाई नागरिकों के बच्चों और पोते-पोतियों के लिए।" }, "4H": { title: "वैश्विक प्रतिभा प्रवासी", desc: "विशेषज्ञता या निवेश क्षमता वाले उच्च उपलब्धि प्राप्त प्रवासियों के लिए।" } },
        benefits: { stay: { title: "असीमित प्रवास", desc: "अब और विस्तार नहीं। जब तक पात्रता मानदंड पूरे होते हैं, आपकी स्थिति स्थायी है।" }, work: { title: "कार्य अधिकार", desc: "बिना किसी अलग IMTA या वर्क परमिट के इंडोनेशिया में स्वतंत्र रूप से काम करें।" }, property: { title: "संपत्ति स्वामित्व", desc: "मानक विदेशी परमिट की तुलना में इंडोनेशिया में संपत्ति के स्वामित्व का आसान रास्ता।" }, entry: { title: "पुन: प्रवेश की स्वतंत्रता", desc: "जीवन भर के लिए वैध कई पुन: प्रवेश परमिट। स्वतंत्र रूप से आएं और जाएं।" } },
        advantage: { title: "GCI लाभ", table: { feature: "विशेषता", gci: "GCI स्थिति", golden: "गोल्डन वीजा", kitas: "ITAS/ITAP", validity_label: "वैधता", unlimited: "असीमित", investment_label: "निवेश की आवश्यकता", none: "कोई नहीं (रक्त संबंध)" } },
        security: { title: "<highlight>IDiv Infinity™</highlight> द्वारा सुरक्षित", desc: "आपकी GCI स्थिति एक विशेष गोल्ड वैरिएंट IDiv कार्ड के साथ जारी की जाती है, जिसमें अद्वितीय इन्फिनिटी आइकन होता है - जो इंडोनेशिया के साथ आपके जीवन भर के बंधन का प्रतीक है।", feature1: "स्मार्ट क्यूआर सत्यापन", feature2: "दोहरी परत होलोग्राम", feature3: "जीवन पर्यंत स्थिति जांच" },
        cta: { title: "क्या आप अपनी विरासत को सुरक्षित रखने के लिए तैयार हैं?", subtitle: "आज ही हमारी विशेषज्ञ कानूनी टीम के साथ ग्लोबल सिटीजन प्रोग्राम में शामिल हों।", placeholder: "ईमेल पता", button: "आवेदन शुरू करें" },
        activity: { secured: "अभी GCI सत्यापन प्राप्त किया", applying: "GCI लाभों के लिए आवेदन कर रहे हैं", researching: "संपत्ति अधिकारों पर शोध कर रहे हैं", verifying: "प्रवासी स्थिति का सत्यापन कर रहे हैं" }
    },
    tr: {
        hero: { title: "Endonezya Diasporası İçin <br /> <highlight>Ömür Boyuk Miras</highlight>", description: "Dünyanın en sağlam Global Citizen of Indonesia (GCI) ikamet statüsü ile Endonezya ile olan kan bağlarınızı koruyun. Ömür boyu sınırsız çalışma haklarının, mülk sahipliğinin ve giriş özgürlüğünün tadını çıkarın." },
        marquee: { item1: "Ömür Boyu İkamet Statüsü", item2: "Tam Çalışma Hakları", item3: "Diaspora Önceliği", item4: "Sınırsız Yeniden Giriş" },
        bonding: { title: "Bağları Korumak, Geleceği İnşa Etmek", quote: "\"GCI bir izinden daha fazlasıdır; Endonezya'nın çocuklarının, nerede olurlarsa olsunlar, her zaman dönecek bir yuvaları olacağının ilanıdır.\"" },
        eligibility: { title: "Etkileşimli Uygunluk Filtresi", subtitle: "GCI gereksinimlerini görmek için profilinizi seçin", "4C": { title: "Eks-WNI (Eski Vatandaşlar)", desc: "Geçmişte Endonezya vatandaşlığına sahip olanlar için özeldir." }, "4D": { title: "Doğrudan Torunlar", desc: "Mevcut veya eski Endonezya vatandaşlarının çocukları ve torunları içindir." }, "4H": { title: "Küresel Yetenek Diasporası", desc: "Uzmanlık alanlarında yüksek başarı gösteren veya yatırım potansiyeli olan diaspora üyeleri içindir." } },
        benefits: { stay: { title: "Sınırsız Konaklama", desc: "Artık uzatma yok. Uygunluk kriterleri karşılandığı sürece statünüz kalıcıdır." }, work: { title: "Çalışma Hakları", desc: "Ayrı bir IMTA veya Çalışma İzni gerekmeden Endonezya'da özgürce çalışın." }, property: { title: "Mülk Sahipliği", desc: "Standart yabancı izinlerine kıyasla Endonezya'da mülk sahibi olmanın daha kolay yolu." }, entry: { title: "Yeniden Giriş Özgürlüğü", desc: "Ömür boyu geçerli çoklu yeniden giriş izinleri. Özgürce uçun." } },
        advantage: { title: "GCI Avantajı", table: { feature: "Özellik", gci: "GCI Statüsü", golden: "Golden Visa", kitas: "ITAS/ITAP", validity_label: "Geçerlilik", unlimited: "SINIRSIZ", investment_label: "Yatırım Şartı", none: "YOK (Kan Bağı)" } },
        security: { title: "<highlight>IDiv Infinity™</highlight> ile Güvende", desc: "GCI statünüz, benzersiz sonsuzluk ikonuna sahip özel Gold Varyant IDiv Kart ile verilir—Endonezya ile olan ömür boyu bağınızın bir işareti.", feature1: "Akıllı QR Doğrulama", feature2: "Çift Katmanlı Hologram", feature3: "Ömür Boyu Statü Kontrolü" },
        cta: { title: "Mirasınızı korumaya hazır mısınız?", subtitle: "Uzman hukuk ekibimizle bugün Global Citizen programına katılın.", placeholder: "E-posta Adresi", button: "Başvuruyu Başlat" },
        activity: { secured: "Az önce GCI Doğrulamasını tamamladı", applying: "GCI Avantajları için başvuruyor", researching: "Mülkiyet Haklarını araştırıyor", verifying: "Diaspora Statüsünü doğruluyor" }
    }
};

// Add remaining languages (simplified logic for the script execution)
const baseLocale = 'en';
const targetDir = path.join(__dirname, 'messages');

async function sync() {
    for (const locale of locales) {
        const filePath = path.join(targetDir, `${locale}.json`);
        if (fs.existsSync(filePath)) {
            let content = JSON.parse(fs.readFileSync(filePath, 'utf8'));
            content.gci = translations[locale] || translations[baseLocale];
            fs.writeFileSync(filePath, JSON.stringify(content, null, 4), 'utf8');
            console.log(`[GCI SYNC] ${locale}.json updated.`);
        }
    }
}

sync();
