// ISO 3166-1 alpha-2 codes for flags
export const COUNTRY_DATA = [
    { name: "Albania", code: "AL", isSpecial: false },
    { name: "Afghanistan", code: "AF", isSpecial: true }, // Calling Visa
    { name: "Andorra", code: "AD", isSpecial: false },
    { name: "Argentina", code: "AR", isSpecial: false },
    { name: "Armenia", code: "AM", isSpecial: false },
    { name: "Australia", code: "AU", isSpecial: false },
    { name: "Austria", code: "AT", isSpecial: false },
    { name: "Azerbaijan", code: "AZ", isSpecial: false },
    { name: "Bahrain", code: "BH", isSpecial: false },
    { name: "Belarus", code: "BY", isSpecial: false },
    { name: "Belgium", code: "BE", isSpecial: false },
    { name: "Bosnia and Herzegovina", code: "BA", isSpecial: false },
    { name: "Brazil", code: "BR", isSpecial: false },
    { name: "Brunei Darussalam", code: "BN", isSpecial: false },
    { name: "Bulgaria", code: "BG", isSpecial: false },
    { name: "Cambodia", code: "KH", isSpecial: false },
    { name: "Cameroon", code: "CM", isSpecial: true }, // Calling Visa
    { name: "Canada", code: "CA", isSpecial: false },
    { name: "Chile", code: "CL", isSpecial: false },
    { name: "China", code: "CN", isSpecial: false },
    { name: "Colombia", code: "CO", isSpecial: false },
    { name: "Croatia", code: "HR", isSpecial: false },
    { name: "Cyprus", code: "CY", isSpecial: false },
    { name: "Czech Republic", code: "CZ", isSpecial: false },
    { name: "Denmark", code: "DK", isSpecial: false },
    { name: "Ecuador", code: "EC", isSpecial: false },
    { name: "Egypt", code: "EG", isSpecial: false },
    { name: "Estonia", code: "EE", isSpecial: false },
    { name: "Finland", code: "FI", isSpecial: false },
    { name: "France", code: "FR", isSpecial: false },
    { name: "Germany", code: "DE", isSpecial: false },
    { name: "Greece", code: "GR", isSpecial: false },
    { name: "Guatemala", code: "GT", isSpecial: false },
    { name: "Guinea", code: "GN", isSpecial: true }, // Calling Visa
    { name: "Hong Kong", code: "HK", isSpecial: false },
    { name: "Hungary", code: "HU", isSpecial: false },
    { name: "Iceland", code: "IS", isSpecial: false },
    { name: "India", code: "IN", isSpecial: false },
    { name: "Ireland", code: "IE", isSpecial: false },
    { name: "Israel", code: "IL", isSpecial: true }, // Calling Visa
    { name: "Italy", code: "IT", isSpecial: false },
    { name: "Japan", code: "JP", isSpecial: false },
    { name: "Jordan", code: "JO", isSpecial: false },
    { name: "Kazakhstan", code: "KZ", isSpecial: false },
    { name: "Kenya", code: "KE", isSpecial: false },
    { name: "Kuwait", code: "KW", isSpecial: false },
    { name: "Laos", code: "LA", isSpecial: false },
    { name: "Latvia", code: "LV", isSpecial: false },
    { name: "Liberia", code: "LR", isSpecial: true }, // Calling Visa
    { name: "Liechtenstein", code: "LI", isSpecial: false },
    { name: "Lithuania", code: "LT", isSpecial: false },
    { name: "Luxembourg", code: "LU", isSpecial: false },
    { name: "Malaysia", code: "MY", isSpecial: false },
    { name: "Maldives", code: "MV", isSpecial: false },
    { name: "Malta", code: "MT", isSpecial: false },
    { name: "Mauritius", code: "MU", isSpecial: false },
    { name: "Mexico", code: "MX", isSpecial: false },
    { name: "Monaco", code: "MC", isSpecial: false },
    { name: "Mongolia", code: "MN", isSpecial: false },
    { name: "Morocco", code: "MA", isSpecial: false },
    { name: "Mozambique", code: "MZ", isSpecial: false },
    { name: "Myanmar", code: "MM", isSpecial: false },
    { name: "Netherlands", code: "NL", isSpecial: false },
    { name: "New Zealand", code: "NZ", isSpecial: false },
    { name: "Nigeria", code: "NG", isSpecial: true }, // Calling Visa
    { name: "North Korea", code: "KP", isSpecial: true }, // Calling Visa
    { name: "Norway", code: "NO", isSpecial: false },
    { name: "Oman", code: "OM", isSpecial: false },
    { name: "Palestine", code: "PS", isSpecial: false },
    { name: "Papua New Guinea", code: "PG", isSpecial: false },
    { name: "Peru", code: "PE", isSpecial: false },
    { name: "Philippines", code: "PH", isSpecial: false },
    { name: "Poland", code: "PL", isSpecial: false },
    { name: "Portugal", code: "PT", isSpecial: false },
    { name: "Qatar", code: "QA", isSpecial: false },
    { name: "Romania", code: "RO", isSpecial: false },
    { name: "Russia", code: "RU", isSpecial: false },
    { name: "Rwanda", code: "RW", isSpecial: false },
    { name: "Saudi Arabia", code: "SA", isSpecial: false },
    { name: "Serbia", code: "RS", isSpecial: false },
    { name: "Seychelles", code: "SC", isSpecial: false },
    { name: "Singapore", code: "SG", isSpecial: false },
    { name: "Slovakia", code: "SK", isSpecial: false },
    { name: "Slovenia", code: "SI", isSpecial: false },
    { name: "Somalia", code: "SO", isSpecial: true }, // Calling Visa
    { name: "South Africa", code: "ZA", isSpecial: false },
    { name: "South Korea", code: "KR", isSpecial: false },
    { name: "Spain", code: "ES", isSpecial: false },
    { name: "Suriname", code: "SR", isSpecial: false },
    { name: "Sweden", code: "SE", isSpecial: false },
    { name: "Switzerland", code: "CH", isSpecial: false },
    { name: "Taiwan", code: "TW", isSpecial: false },
    { name: "Tanzania", code: "TZ", isSpecial: false },
    { name: "Thailand", code: "TH", isSpecial: false },
    { name: "Timor-Leste", code: "TL", isSpecial: false },
    { name: "Tunisia", code: "TN", isSpecial: false },
    { name: "Turkey", code: "TR", isSpecial: false },
    { name: "Ukraine", code: "UA", isSpecial: false },
    { name: "United Arab Emirates", code: "AE", isSpecial: false },
    { name: "United Kingdom", code: "GB", isSpecial: false },
    { name: "United States", code: "US", isSpecial: false },
    { name: "Uzbekistan", code: "UZ", isSpecial: false },
    { name: "Vatican", code: "VA", isSpecial: false },
    { name: "Venezuela", code: "VE", isSpecial: false },
    { name: "Vietnam", code: "VN", isSpecial: false }
].sort((a, b) => a.name.localeCompare(b.name));

// Keeping backward compatibility if needed, but StepCountryVisa should use COUNTRY_DATA
export const STANDARD_COUNTRIES = COUNTRY_DATA.filter(c => !c.isSpecial).map(c => c.name);
export const SPECIAL_COUNTRIES = COUNTRY_DATA.filter(c => c.isSpecial).map(c => c.name);
