export interface PhoneCode {
    name: string;
    code: string;
    initial: string;
    dialCode: string;
}

export const PHONE_CODES: PhoneCode[] = [
    { name: "Indonesia", code: "ID", initial: "IDN", dialCode: "+62" },
    { name: "Australia", code: "AU", initial: "AUS", dialCode: "+61" },
    { name: "China", code: "CN", initial: "CHN", dialCode: "+86" },
    { name: "India", code: "IN", initial: "IND", dialCode: "+91" },
    { name: "Japan", code: "JP", initial: "JPN", dialCode: "+81" },
    { name: "Malaysia", code: "MY", initial: "MYS", dialCode: "+60" },
    { name: "Singapore", code: "SG", initial: "SGP", dialCode: "+65" },
    { name: "South Korea", code: "KR", initial: "KOR", dialCode: "+82" },
    { name: "United States", code: "US", initial: "USA", dialCode: "+1" },
    { name: "United Kingdom", code: "GB", initial: "GBR", dialCode: "+44" },
    { name: "France", code: "FR", initial: "FRA", dialCode: "+33" },
    { name: "Germany", code: "DE", initial: "DEU", dialCode: "+49" },
    { name: "Russia", code: "RU", initial: "RUS", dialCode: "+7" },
    { name: "Netherlands", code: "NL", initial: "NLD", dialCode: "+31" },
    { name: "Italy", code: "IT", initial: "ITA", dialCode: "+39" },
    { name: "Spain", code: "ES", initial: "ESP", dialCode: "+34" },
    { name: "Canada", code: "CA", initial: "CAN", dialCode: "+1" },
    { name: "New Zealand", code: "NZ", initial: "NZL", dialCode: "+64" },
    { name: "Saudi Arabia", code: "SA", initial: "SAU", dialCode: "+966" },
    { name: "United Arab Emirates", code: "AE", initial: "ARE", dialCode: "+971" },
    { name: "Philippines", code: "PH", initial: "PHL", dialCode: "+63" },
    { name: "Thailand", code: "TH", initial: "THA", dialCode: "+66" },
    { name: "Vietnam", code: "VN", initial: "VNM", dialCode: "+84" },
    { name: "Brazil", code: "BR", initial: "BRA", dialCode: "+55" },
    { name: "Mexico", code: "MX", initial: "MEX", dialCode: "+52" },
    { name: "Switzerland", code: "CH", initial: "CHE", dialCode: "+41" },
    { name: "Sweden", code: "SE", initial: "SWE", dialCode: "+46" },
    { name: "Norway", code: "NO", initial: "NOR", dialCode: "+47" },
    { name: "Denmark", code: "DK", initial: "DNK", dialCode: "+45" },
    { name: "Ukraine", code: "UA", initial: "UKR", dialCode: "+380" },
    { name: "Turkey", code: "TR", initial: "TUR", dialCode: "+90" },
    { name: "South Africa", code: "ZA", initial: "ZAF", dialCode: "+27" },
    { name: "Egypt", code: "EG", initial: "EGY", dialCode: "+20" },
    { name: "Nigeria", code: "NG", initial: "NGA", dialCode: "+234" },
    { name: "Pakistan", code: "PK", initial: "PAK", dialCode: "+92" },
    { name: "Bangladesh", code: "BD", initial: "BGD", dialCode: "+880" },
    { name: "Iran", code: "IR", initial: "IRN", dialCode: "+98" },
    { name: "Israel", code: "IL", initial: "ISR", dialCode: "+972" },
    { name: "Belgium", code: "BE", initial: "BEL", dialCode: "+32" },
    { name: "Poland", code: "PL", initial: "POL", dialCode: "+48" },
    { name: "Portugal", code: "PT", initial: "PRT", dialCode: "+351" },
    { name: "Greece", code: "GR", initial: "GRC", dialCode: "+30" },
    { name: "Ireland", code: "IE", initial: "IRL", dialCode: "+353" },
    { name: "Austria", code: "AT", initial: "AUT", dialCode: "+43" },
    { name: "Finland", code: "FI", initial: "FIN", dialCode: "+358" },
    { name: "Czech Republic", code: "CZ", initial: "CZE", dialCode: "+420" },
    { name: "Hungary", code: "HU", initial: "HUN", dialCode: "+36" },
    { name: "Romania", code: "RO", initial: "ROU", dialCode: "+40" },
    { name: "Argentina", code: "AR", initial: "ARG", dialCode: "+54" },
    { name: "Colombia", code: "CO", initial: "COL", dialCode: "+57" },
    { name: "Chile", code: "CL", initial: "CHL", dialCode: "+56" },
    { name: "Peru", code: "PE", initial: "PER", dialCode: "+51" },
    { name: "Hong Kong", code: "HK", initial: "HKG", dialCode: "+852" },
    { name: "Taiwan", code: "TW", initial: "TWN", dialCode: "+886" }
].sort((a, b) => a.name.localeCompare(b.name));
